import React from 'react';
import { useHistory } from "react-router-dom";
import Button from '@mui/material/Button';
import stjoseph from '../../img/stjoseph.jpg';
import kcreddy from '../../img/kcreddy.jpg';
import convocation from '../../img/convocation.png'
import cftriopening from '../../img/cftriopening.png'


export default function Cftri() {
    const history = useHistory();
    const onClickHome = (event) => {
        history.push("/");
    }

    return (
        <>
            <div style={{
                backgroundImage: "url(" + stjoseph + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat',
                width: '100%',
                height: '155px'
            }} />
            <div className="container" >
                <br></br>
                <div className="earlylife" >Central Food Technology Research Institute (CFTRI)</div>
                <br></br>
                <div className="earlylifepara" >The Cheluvamba Palace was a building constructed for the residence of Cheluvajamanni, who was the Maharaja's sister. The building was not in use for some years until December 29th 1948, where it was handed over to the Prime Minister Nehru by Jayachamarajendra Wadiyar.</div>
                <div className="earlylifepara" ><a href="cheluvajamanni" style={{ textDecoration: 'none', color: '#3819e9' }} >More about Cheluvajamanni, Third Maharani Kumari and Cheluvamba Palace</a></div>
                <br></br>
                <div>
                    <img style={{ float: 'left', margin: '15px' }} src={kcreddy} height={250} width={200} />
                    <div className="earlylifepara" >The Cheluvamba Palace remained vacant for a few years when it reverted to the Maharaja. The Government of Mysore had also generously offered a palatial building called "Cheluvamba Mansion" to the World Health Organization. As luck would have it within a few days the WHO announced their intention to locate their headquarters in Delhi"<a href="/references" style={{ textDecoration: 'none', color: "#3819e9" }} >(1)</a>. K.C. Reddy (1902-1976 ) the first Chief Minister of Mysore - <font size="3" style={{fontStyle: "italic"}} >in the picture to the left</font>, was deeply interested that  Food Technological Research Institute to be located in Mysore. Subrahmanyam, has said that K.C. Reddy telegraphed Nehru to fix a date for his visit to Mysore, even before the formal decision of then Maharaja, Jayachamarajendra Wadiyar to hand over the building (Cheluvamba Palace) and that when finally handed over it was at a rent of Rs. One per year. This rent was perhaps charged till the complete integration of Mysore state with the rest of India. The state was still under dyarchy at that time of take over of the building by the Government of India.</div>
                </div>
                <br></br>
                <div>
                    <img style={{ float: 'left', margin: '15px' }} src={convocation} height={220} width={380} />
                    <div className="earlylifepara" >Nehru visited Bangalore and Mysore in December 1948. He visited the Indian Institute of Science, drove to Mysore. He was awarded a Doctor of Science degree from the University of Mysore on 28th December 1948 and In the afternoon of the 28th December, 1948 Pandit Nehru witnessed the famous Khedda operations at Kakankote. <font size="3" style={{ fontStyle: "italic" }} >In Picture: Convocation conferring the honorary Doctor of Science by the Chancellor Jayachamarajendra Wadiyar.</font></div>
                    <div className="earlylifepara" >A river drive was arranged and about thirteen wild elephants were captured on that day. Coming back to Mysore by dusk Pandit Nehru visited the Krishnaraja Sagar Dam and the Brindavan Garden. At Hotel Krishnaraja Sagar he attended a banquet given in his honour and came back to Mysore late in the night. On the morning of the 29th, he received on behalf of the Government of India the building known as the "Cheluvamba Mansion", meant to house the Food Technological Institute of the Government of India.<a href="/references" style={{ textDecoration: 'none', color: '#3819e9' }} >(2)</a>.The third international forestry and timber utilization conference Asia and the Pacific convened by the FAO was held in the Cheluvamba Mansion Mysore in March 1949 <a href="/references" style={{ textDecoration: 'none', color: '#3819e9' }} >(3)</a>. In April 1949 the building was transferred to the Government of India.</div>
                    <div className="earlylifepara" >"Mysore is grateful to the Government of India for locating the All-India Food Technological Institute Within her borders and it is with the greatest pleasure that she has place at the government of India's disposal the spacious buildings and part of the grounds of the Cheluvamba Mansions for the housing of the Institute and its Laboratories. She is also glad that the proposal to add the Fruit Technology Section to the Institute is under active consideration" says K.C. Reddy in 1949.<a href="/references" style={{ textDecoration: 'none', color: '#3819e9' }} >(3)</a></div>
                </div>
                <br></br>
                <div>
                    <img style={{ float: 'left', margin: '15px' }} src={cftriopening} height={250} width={380} />
                    <div className="earlylifepara" >The Central Food Technological Research Institute, Mysore, was declared open by the Hon'ble Sri C. Rajagopalachari, on October 21, 1950. The Rajpramukh, the Maharaja of Mysore, presided. The function, which took place in a special panda at the Cheluvamba Mansions, was attended by eminent men of science, officials of the Central and State governments and prominent citizens.</div>
                    <div><font size="3" style={{ fontStyle: 'italic' }} >In Picture : Mr. C. Rajagopalchari (Minister without Portfolio) and Jayachamarajendra Wadiyar in the center. S.S. Bhatnagar to the left. K.C. Reddy to the right (not clear).</font></div>
                </div>
                <br></br>
                <div className="earlylifepara" >The Institute, the fifth in the chain of national laboratories declared open this year, is housed in the magnificent Cheluvamba Mansion, which was taken over by the Government of India in April 1949. The establishment of the Institute was recommended by the Industrial Research Planning Committee of the Council of Scientific & Industrial Research in 1945. The Governing Body of the Council sanctioned the necessary expenditure for formulating detailed plans for the Institute in February1948. The formal agreement regarding the location of the Institute at the Cheluvamba Mansions, Mysore, was reached in December 1948, and the work connected with the planning and organization of the laboratories was entrusted to Dr. V. Subrahmanyan, since appointed Director of the Institute. The arrangements for converting the palace into a laboratory commenced in April 1949, and before the end of the year, the Biochemistry and Nutrition Divisions and a section of the Processing Division were actively functioning. Early in 1950  the Indian Institute of Fruit Technology was merged  with   the   Institute  and   by  July of the same year the Division of Fruit Technology was  fully organized,  not only for carrying out researches on the preservation and processing of fruits and vegetables, but also for  conducting  the  All India Postgraduate Diploma Course in Fruit Technology.</div>
                <br></br>
                <div className="earlylifepara" >Declaring the Institute open, C. Rajagopalachari paid a tribute to the work of Dr. Shanti Swarup Bhatnagar in speedily establishing the national laboratories in the country. He drew attention to the vast scope for research in solving the food problems facing the country, and suggested that scientific research and technological processes should be employed to minimize all forms of food wastage and to preserve all surplus food material. Another field for investigation, he said, "is the elimination of the harmful constituents of non-edible materials, and the conversion of the latter in to healthy and attractive food. This also is a vast and very important field of investigation in the plan of supplementing our food resources. Closely linked up with this is the maintenance of nutritional standards by the use of staple subsidiary foods. There is again the problem of the manufacture of concentrated foods and accessories like vitamins on a large scale which would assist the maintenance of proper nutritional standards in India".</div>
                <br></br>
                <div className="earlylifepara" >In his speech the Rajpramukh, the Maharaja of Mysore, observed that the importance of food cannot be over-emphasized in a poor under-nourished country like India." This Institute ", he observed," is one amongst the many enterprises that are evidence of the innate constructive genius of our Nation. Our Government, since the advent of Swaraj, has been trying to liquidate the arrears of centuries in the matter of scientific, industrial and material progress. Think of the many research laboratories it has organized; of the many dams and reservoirs it has planned for the conservation of waters needed in our dry and droughty land; of the many power stations that are in the stage of planning or actually under construction for the improvement of the economic condition of our people; of the encouragement it has given to ship building; and of the many research laboratories -   pure and applied:  it is establishing all over the country and the stimulus and support it has given to research and creative activities." Speaking of the conservative food habits of the people of India and how the people at large are apt to be reluctant to utilize new food products, he stressed the role of educated and upper strata of society in setting an example by be taking to such food products.</div>
                <br></br>
                <div className="earlylifepara" >Dr. S. S. Bhatnagar, in an illuminating address on the occasion, briefly traced  the circumstances leading to the establishment of the Institute, and observed, "Today's inauguration of this Institute is the first big step which the Government of India have taken to solve the food problem by the technological, as distinguished from the purely biological, methods. New food industries such as the manufacture of breakfast cereals and food yeast are being established in the country, and for their proper development, a Central Food Technological Research Institute is a real necessity." He assured the gathering that within a year of its inauguration, the Institute will make distinct contributions towards the solution of food shortage in India. He paid a tribute   to the work of Dr. V. Subrahmanyan, who has worked zealously and hard to establish, as quickly as possible, this new aid to food industry.</div>
                <br></br>
                <div className="earlylifepara" >In his message Pandit Jawaharlal Nehru, the Prime Minister of India, referred to the scientific developments in the country during the past few years and said: "One of the remarkable developments in India, during the last three years, has been the opening of national laboratories and research institutes. We have put up some magnificent laboratories, not only impressive to look at, but I hope, the homes of productive effort and work. It is ultimately on the basis of work done in our research institutes and laboratories that we can progress in most directions. Thus far we have depended on other countries and have merely copied them or taken advantage of something that they have done. We cannot go far with this dependence. We have at least laid good and true foundations for scientific progress. It is for the young scientists of India to take advantage of the great opportunities   offered to them and thus help in building up the New India. "We have given top priority to the production of food grains or subsidiary foods. It is obvious that food is of the first importance and its value cannot be judged merely in money terms. We cannot depend on imports for our food and, therefore, we have laid down a target for food sufficiency.    This is the 1951-1952 season. In spite of all difficulties and disasters, we still adhere to that target and are trying to work up to it. We hope to succeed. It must always be remembered that food production has the highest priority. "How can science help in this? The primary responsibility is of our Department of Agriculture. Science can help in agriculture greatly. It can also help in various other processes. It is particularly with these other processes that this Institute will be concerned. I hope the work done in this Institute will bear fruit not in developments on paper and in scientific journals but in terms of human values and in increase of suitable food for our people."</div>
                <div className="earlylifepara" >The functions of the Central Food Technological Institute include:</div>
                <div className="earlylifepara" >
                    <ul style={{ color: "rgb(42, 42, 42)" }} >
                        <li>Development of improved methods of storage; refrigeration, freezing, gas storage, dehydration, canning, etc; study of biochemical and microbiological changes accompanying spoilage; reclamation and utilization of infested or otherwise affected food materials ;</li>
                        <li>Processing of food stuffs with a view to</li>
                        <li>Facilitating their ready usage, and</li>
                        <li>Improving their keeping quality; treatment of coarse materials to improve palatability, digestibility and food value; elimination of harmful and unpalatable ingredients from food materials;</li>
                        <li>Study of new and unfamiliar sources of food materials and processing of new materials to render them suitable for human consumption, emergency foods, survey of potential food resources in different regions.</li>
                        <li>Production of concentrated foods, vitamins and other food accessories, composite multi-purpose foods, supplementary foods, substitutes, etc.</li>
                        <li>Dietetics, design and demonstration of improved types of food preparations to suit the economic conditions and sentiments of people in different regions; studies on cooking utensils; improved cooking methods with a view to saving in labor and minimizing the consumption of fuel;</li>
                        <li>Study of problems relating to food industries; provision of technological information required by industry; survey of existing industries and their technical problems and collection of factual data for development of new industries; pilot plant trials;</li>
                        <li>Food sanitation, survey and advice on hygienic conditions for food industries;</li>
                        <li>Food adulteration; development of new methods of detection and quality control and food information; dissemination of general information on food and dietary problems through bulletins and technological reports.</li>
                    </ul>
                </div>
                <div className="earlylifepara" >The work of the Institute will be carried out through the following Divisions: Biochemistry and Nutrition, Processing, Storage and Preservation, Quality Control, Microbiology and Sanitation, Engineering, and Information and Statistics. A Division of Dietetics and a Section for Food Containers are also being organized. The Institute will soon have a staff of over 200, including 70 scientific workers.  As the activities develop, additional staff will be recruited. The Institute may also have to establish centers and regional laboratories which will work in close association with the Central Laboratory. The Institute is now in receipt of a recurring and capital grant aggregating to about Rs.  9 lakhs, but this is expected to increase steadily with the opening up of new Divisions and other activities" <a href="/references" style={{ textDecoration: 'none', color: '#3819e9' }} >(5,6)</a></div>
                <div className="earlylifepara" ><a href="/references" style={{ textDecoration: 'none' }} ><font color="#3819e9">References</font></a></div>
                <br></br>
                <Button size="small" style={{ color: 'white', fontWeight: 'bold', backgroundColor: 'darkblue', width: '155px', height: '35px' }} onClick={onClickHome} >Back to Home</Button>
            </div>
        </>
    )
}