import React from 'react';
import { useHistory } from "react-router-dom";
import Button from '@mui/material/Button';
import stjoseph from '../../../img/stjoseph.jpg'
import amul1 from '../../../img/amul1.jpg'
import amul2 from '../../../img/amul2.jpg'
import amul3 from '../../../img/amul3.jpg'
import larsenandturbo from '../../../img/larsenandturbo.jpg'

export default function InfantFood() {
    const history = useHistory();
    const onClickHome = (event) => {
        history.push("/");
    }

    return (
        <>
            <div style={{
                backgroundImage: "url(" + stjoseph + ")",
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat',
                width: '100%',
                height: '155px'
            }} />
            <div className="container" >
                <br></br>
                <div className="earlylife" >Amul Milk Powder</div>
                <br></br>
                <div className="earlylife" style={{ fontSize: 'larger' }} >Development of Amul Baby food</div>
                <br></br>
                <div className="earlylifepara" >India became the first country in the world to produce baby and Infant food from Buffalo milk in the years 1950-1962. This established the pre-eminence of Amul in the manufacture of this product. The CFTRI, CSIR and the NRDC in their many web sites (<a href="https://blog.mygov.in" target="_blank" style={{ textDecoration: 'none', color: '#3819e9' }} >https://blog.mygov.in</a> > csirs-breakthrough-in-baby-food; <a href="http://www.nrdcindia.com" target="_blank" style={{ textDecoration: 'none', color: '#3819e9' }} > http://www.nrdcindia.com</a> > SucessStory; <a href="http://www.niscair.res.in" target="_blank" style={{ textDecoration: 'none', color: '#3819e9' }} >http://www.niscair.res.in</a> > images > csirnews_jul10); <a href="" target="_blank" style={{ textDecoration: 'none', color: '#3819e9' }} >Celebrating the successes of science in post-independence India-IndiaBioscience</a>) as well as government records of the time (4) proclaim that the CFTRI at Mysore was instrumental in development of the process. Verghese Kurien in the versions that refer to him denies this. However Amul in its own advertisements have acknowledged the role of the CFTRI especially the fact that the Raffi Ahmed Kidwai prize for 1960 was given to a CFTRI team for development of the process. Subrahmanyan who was director at the C.F.T.R.I. at that time has occasionally referred to the role of the CFTRI in development of the process. We now present the story in his own words and in subsequent chapter summarize publications on the process from the C.F.T.R.I. Lastly biographies of some of those from the C.F.T.R.I. who contributed to the development of the process is appended here, <a href="/biographies" style={{ textDecoration: 'none', color: '#3819e9' }} >Click to know more.</a></div>
                <br></br>
                <div className="earlylife" style={{ fontSize: 'larger' }} >Differing Versions </div>
                <br></br>
                <div className="earlylifepara" >Noram Wright, Director of the Hannah Dairy Research Institute, Ayrshire, Scotland visited India on a  survey of the Dairy industry in the country from the 4th November 1936 to 25th March 1937 published a report published by the then Government of India.  The report is a very detailed analysis of the state of dairying in the country. However he noted that while  India was a large producer of milk, she was unable to use its own resources. A village based industry making ghee and other milk products were suggested. It is interesting that in that report he did not foresee the development of a milk powder/infant food industry. India in the years 1952-54 was according to Terrence McCabe, the second largest importer of  milk products in the world even though India has "almost a fourth of the cattle in the world and more than half the water buffaloes"</div>
                <div className="earlylifepara" >A large part of the imports particularly, milk powder, was by the UNICEF for distribution to needy children. "The Government of India has recently indicated that it intends to capture at least part of its own internal market. Various departments of the Government have during the last several months recommended setting up of from 9 to 22 milk dairying plants in the country during the next five years in several of the installations".2 The government expected to have the financial assistance for the UNICEF which would provide for  free distribution to needy children</div>
                <br></br>
                <div className="earlylife" style={{ fontSize: 'larger' }} >Report of the Milk Committee and in the Lok Sabha </div>
                <br></br>
                <div className="earlylifepara" >The Anand milk powder factory was established and was function in 1955. Shrimathi Ila Palchoudhay(3) asked in 1956 at the Lokh Sabha as to (A) Whether it is a fact that a milk drying plant the first of its kind in the world to dry buffalo milk was set up in India last year under the auspices of the UNICEF; b) if so, the total cost involved in its construction c) It's annual production capacity d) The date of it's going into production and e) The place of location. The answer given Dr.P.S. Deshmukh (Minister of Agriculture) a) Yes. b) Rs.40 Lakhs according to information furnished by the union c) 1000 tons d) 31st October 1955 (Inaugurated by Jawaharlal Nehru) c) Anand in Bombay (now Gujarat) state.</div>
                <br></br>
                <div className="earlylifepara" >A committee, The Milk Committee, appointed by the Commerce and Industry Ministry, Government of India, to look into various aspects of milk processing in India, submitted its report on February 19th, 1957. Mr. Krishan Chand was Joint Secretary, Ministry of Food and Agriculture was chairman. Dr. L.C. Sikka, a prominent scientist, was on the committee. The report began with a discussion of milk imports and stated that about 3000 long tons (one long ton equals nearly 1,016. kg) of dried whole milk and 3500 of milk foods for infants and invalids were imported during 1953-55. 1n 1938 a firm from Kolkata firm, National Nutriment Limited, began commercial production of milk powder from local milk suppliers including the roller process, import restrictions import scarcity of foreign supplies created a profitable internal trade during the War period. They established three roller drying plants (James Bell  PTY Ltd Melbourne Australia). They were installed near Calcutta,  Varanasi and in erstwhile East Pakistan. After the war the firm could not compete with imported products in either quality or price (as there was much milk powder provided by the UNICEF) and in 1951 it ceased operation before deciding to go out of business</div>
                <br></br>
                <div className="earlylifepara" >The milk committee report goes on to state that "the Council of Scientific and Industrial Research sanctioned a grant to enable the Kaira District Cooperative Milk Producers Union Ltd.to manufacture baby food according to the formula of the Central Food Technological Research, Mysore. Feeding trials have been carried out with the baby food thus manufactured." (It is not clear whether this was so as it has been reported that the NRDC that provided Amul with Rs. 10,000 to Kaira District Milk Producers Union for large scale production of baby food using the spray drying process). </div>
                <br></br>
                <div className="earlylifepara" >"The Central Food Technological Research Laboratory has evolved a process for the manufacture of infant milk from buffalo milk and this process is at present being exploited by M/S Kaira Dt. Cooperative Milk Producers Union Ltd, Anand. They have been granted a license under Industries (Development and regulation) act for producing 2500 tons of baby food per annum. Permission has been granted to M/S Glaxo Laboratories with an installed capacity of 2500 tons of infant milk food per annum. The total demand in the country for infant Milk Food is about 50000 to 6000 and Kaira District. Cooperative milk producers union will not meet this demand. The scheme of M/s Glaxo Laboratories did not involve any foreign exchange goods, as this was provided by their parent company Ms Horlicks has been allowed to produce infant food (Melcose Brand) has having an installed capacity of 228 tonnes per annum They will be producing Horlicks malted milk at their factory at Nabha."</div>
                <br></br>
                <div className="earlylife" style={{ fontSize: 'larger' }} >The Kurien Version</div>
                <br></br>
                <div className="earlylifepara" >The  role that  C.F.T.R.I. played has been narrated in almost identical tones in three  books on Kurien (11,12,13). "Amul could not use CFTRI's formula and had to develop one of its own. But Kaira Cooperative, preparing to tackle a multinational firm, dared not antagonize any arm of the government and so it confirmed to the set procedures and applied to the National research Development Corporation of India for a grant to finance the testing of C.F.T.R.I.  grant of ten thousand rupees was sanctioned. In due course Amul made an experimental batch of about 1811kg of baby food for the prescribed trials at Vellore"</div>
                <br></br>
                <div className="earlylifepara" >"How we evolved our baby food formula is an interesting story. We were told that the Central Food Technological Research Institute (CFTRI) had already developed and tested a formula. I had requested the National Research Development Corporation (NRDC) to give us a grant of Rs 10,000 which we could give to the CFTRI for the use of their formula. Dalaya, Molly and I drove down to Ahmedabad for a meeting with Subramaniam, Director of CFTRI. He informed me that Kasturbhai Lalbhai, the Chairman of NRDC, had asked me to meet him at his house for tea. I told them that my colleague Dalaya and my wife would also come with me and I would not come alone. Subramaniam checked with Kasturbhai, who invited all of us. So we all went to Kasturbhai's house. Tea arrived. And then Kasturbhai looked at us and said, 'I expected much older people. I find you are very young. So I better be frank with you.' Then pointing a finger at Subramaniam he said, 'This man is a crook. You think he has made some great discovery. He will give you some half-baked formula and then you will have to spend millions, cleaning up his formula and making it usable.</div>
                <br></br>
                <div className="earlylifepara" >Then you will find that he will go and sell it to Glaxo. You still want that formula?' I said, 'Yes, Sir. I do.' 'All right then, there is no need to discuss anything further,' said Kasturbhai. All through that time, Subramaniam was very silent. The meeting was over. All of us finished our tea and got into my car to drive back. Dalaya and Molly sat in the back seat and I drove. Subramaniam sat next to me in the front. He was extremely nervous and kept on fiddling with his tie. He had never expected this to happen. After about half an hour of complete silence he said, 'He (referring to Kasturbhai) spoke very badly". I said, 'Yes.' Subramaniam continued: 'He had no business to do so. I don't know what made him say that.' We returned to Anand and as it happened, Dalaya realised that we could not use their formula at all. He had to change the formula before it could become usable. And yet we had to pay a huge sum as royalty - Rs 30 to 40 lakh - over the years to the CFTRI through NRDC."</div>
                <br></br>
                <div className="earlylifepara" >Kamath in his account(13)  which in many is very similar to the other two,  mentions that according to "one report" the trials of the C.F.T.R.I. method was after trials at Kaira with the NIRO spray drier was successful and was carried out with the Rs. 10,000 provided by the NRDC.  This was followed by an account of the  in where Subrahmanyan and Kurien met with Kasturbhai Lalbhai at Allahabad. The major grouse the Kurien must have had was the royalty of Rs.35 Lakh to be paid to to the NRDC (This is mentioned in all three versions!). Kamat mentions  the Dallaya  used an single  German air drier and obtained a product with higher solubility. </div>
                <br></br>
                <div className="earlylifepara" >Interestingly the name Subrahmanyan is actually spelt Subramanian in two versions of the Kurien story while his name is not mentioned in one.</div>
                <br></br>
                <div className="earlylifepara" >The UNICEF had funded the purchase of the NIRO atomiser spray dyer for the KAIRA District Milk Producers Union  while the C.F.T.R.I. obtained" a Niro spray drying for pilot plant trials in connection  with malted milk powder, glucose powder and fruit Juice powder" (Bulletin of the C.F.T.R.I.1951-52 volume 1 page 125). Therefore, it appears as though the C.F.R.I. had used the Niro spray dryer even before they had used the large one at Anand(see also Infant Food Part 2)  and "Actually CFTRI had already demonstrated that using the Australian spray drier at Benares a cheaper and more stable product was obtained. Solubility of the spray dried product was always better while the keeping quality of the roller dried product was superior." </div>
                <br></br>
                <div className="earlylife" style={{ fontSize: 'larger' }} >Subrahmanyan's Notes on the Process in his own words</div>
                <br></br>
                <div className="earlylife" style={{ fontSize: 'larger' }} >"A note on the researches, pilot plant studies and negotiations leading to the lease of the process for the production of baby food based on buffalo milk".</div>
                <br></br>
                <div className="earlylifepara" >"It was in the above capacity (Director,CFTRI, Mysore) that I started during the early fifties, a program of research relating to the production of a baby food based on buffalo milk. I realized that, at that time it was only buffalo milk which was available in surplus quantities in some parts of the country. There was need for such a research because all the baby foods produced till then, in different parts of the world were based only on cow's milk and buffalo milk was not being used anywhere for the production of baby food.</div>
                <br></br>
                <div className="earlylifepara" >The work on the subject was started in the early fifties with three senior associates who are still in the institute-Sri M.R. Chandrashekara, Dr.M.Swaminathan and Dr.D.S. Bhatia. The original concept was mine and I realized that India is to make a beginning in the line, it could be only with buffalo milk which is available in surplus quantities in some parts of the country and which can also be produced in still larger quantities, if there is a guaranteed off-take. I also foresaw the practical difficulties in respect of the solubility and digestibility of a product based on buffalo milk. It was with this view that I suggested the addition of buffers that will improve the dispersibility and digestibility of buffalo milk protein. The earlier laboratory work and subsequent trials under subsequent trials under factory conditions were carried out by Shri. Chandrasekhara, to whom we rightly assigned the first place for the Kidwai award. The nutritional evaluations and feeding trials with children were in charge of Dr.Swaminathan. Dr.Bhatia supervised the technological part of the work as had previous experience of similar work at one of the Military dairies in the Punjab. I had entrusted the work jointly to Dr.D.S. Bhatia who was then Head of the Processing Division and to Dr.M.Swaminathan who was then the head of the Division of Nutrition and dietetics. Shri M.Chandrashekara , who was then an Assistant, was  assigned to help in the work, particularly in respect of the preparatory and processing work. I had also given them the guide-lines relating to 1) the elimination of metallic (particularly copper) contamination from the collecting vessels 2) the removal of the excess amount of butter fat, which is generally characteristic of buffalo milk and 3 adjustment of the buffer salts (chiefly citrate and phosphate ) which were deficient in buffalo milk as compared with cow's milk.</div>
                <br></br>
                <div className="earlylifepara" >The present Director (Dr.H.A.B. Parpia) joined the  Institute as an Assistant Director in charge of information Statistics and extension services, at a later date. By that time, we had completed all the technical work and also the preparatory trials. The negotiations with the Kaira Union had also reached the final stage.</div>
                <br></br>
                <div className="earlylifepara" >All the scientific and technological research papers on the subject bear the name of Shri Chandrasekhara, Dr. M.Swaminathan, Bhatia and myself Subsequently we published two more papers bearing on the calculation of costs and this was in collaboration with Dr.Parpia.</div>
                <br></br>
                <div className="earlylifepara" ><a href="/infant-food-paper1" target="_blank" style={{ textDecoration: 'none', color: '#3819e9' }} >To know more about the process click here. </a></div>
                <br></br>
                <div className="earlylife" style={{ fontSize: 'larger' }} >Pilot Plant studies with assistance from the NRDC</div>
                <br></br>
                <div className="earlylifepara" >The work had to be followed up by pilot plant studies to demonstrate the feasibility of commercial production and also to evaluate the product, as compared with the imported preparations, by extensive feeding with babies in different parts of the country, For production of at least a tonne of the product we needed proper equipment and funds, For help in production, I sought the assistance of Mr. (now Dr.) V.Kurien who still is the manager of the Kaira Cooperative Milk Producers Union Anand. Dr.Kurien had then only a spray dyer, but he readily agreed to use it for our trials if we could meet the entire cost. After getting his estimate, I approached the National Research Development Corporation (KRDC) for advance of Rs. 10,000/- towards the cost of the trials. The latter was quickly sanctioned, and I was able to arrange for early production of the trial batch at Anand. Subsequently, Dr.Swaminathan and I arranged for the evaluation studies at a number of centers in different parts of the country. The studies carried out, particularly, at the child centers at Bombay and Calcutta were very valuable  and showed convincingly that our product was comparable, in every respect, with some of the well known brands which were then being imported into our country.</div>
                <br></br>
                <div className="earlylifepara" >There was however some diffidence about the keeping quality (shelf life) of the spray-dried product as the evacuation and gas filling techniques has not then been perfected in our country. As we were aware  some of the well-known and popular bands had been made by roller drying, we looked round for suitable equipment and learnt that one was available at Benares, For this again, we had to pay and the NRDC gave me a further advance towards this trial. I deputed Shri Chandrashekara for this work, so that he may study the operations and arrange for the packing and dispatch of the finalized product. This experiment was also successful.. Storage studies that without any special precautions, roller dried product can keep, for at least a few months without development of rancidity or any off odor. Based on the above findings, I contacted Dr.Kurien, who had expressed keen interest in taking up production. Despite our enthusiasm, Dr. Kurien and I realized that the product was new to our country and required a good marketing organization which had also previous experience in the line. With the prior concurrence of Prof. M.S. Thacker, who was then the Director-General of Scientific and Industrial Research, we contacted Mr.Palmer, who was then the General Manager of Glaxo Laboratories in India. Mr. Palmer was interested but stipulated that his concern should have the entire control over the production and his firm would market the baby food under its own proprietary name, as its own product. We were not agreeable to this proposal. The later efforts of Prof. Thacker, to get a different decision through the head office of the firm in U.K. also proved unfruitful. It was then that Dr.Kurien took the bold decision to take up the manufacture with the resources of his own firm and to get another leading firm (Voltas) to help with the marketing.</div>
                <br></br>
                <div className="earlylifepara" >With the above as the background  and with the prior concurrence of Prof. Thacker, Dr.Kurien and I met Seth Kasturbhai Lalbhai, who was then Chairman of the National Cooperative Development Corporation , at Ahmedabad. At that meeting, Seth Karthurbahi stipulated and Dr.Kurien agreed to pay a royalty for the rights to utilize the process. We were all keen about the development of a new industry in the country and the royalty was intended to be no more than a token. On the basis of this, Dr. Kurien made a formal application and the terms were formally approved by the NRDC at one of its meetings</div>
                <br></br>
                <div className="earlylifepara" >The matter of sharing in the royalties would not have attracted and attention if the process had not proved a success. It proved highly successful and because, in fact, the most important processes leased out by the N.R.D.C. The credit for these successes should go to Shri Kurien and his associates."</div>
                <br></br>
                <div className="earlylife" style={{ fontSize: 'larger' }} >References by the Kaira Diary to the C.F.T.R.I. process</div>
                <br></br>
                <div className="earlylifepara" >In a press note was published in the Indian Dairyman (1960) under the heading "Plant for chesse and baby food: A Rs.31-Lakh factory promoted by the Kaira District Co-operative Milk Producers Union was inaugurated on October 31, 1960 by Shri Moraji Desai, Union Finance Minister at Anand (Kaira dist.)in Gujarat. The union is one of the four firms permitted to set up baby plants in India. The plant at Anand will produce 2500 tons of baby food and one million lbs of cheese a year. The process is automatically controlled and for the time in the country milk will be pasteurized by electronically controlled machines. The baby food formula, originally developed at the Central Food Technological Research Institute, Mysore has been perfected in collaboration of Anand's dairy experts"(6,7).  Amul received ISI certification the next year and the role of the CFTR in in that process was acknowledged8  and tins with  CFTRI mentioned on the lid were released.</div>
                <br></br>
                <div className="earlylifepara" >Further more In contrast to the sharp comments  by Kurien mentioned above, it is clear that in a number of advertisements during the years 1964-1966 at least that the advertisements from Amul have carried openly references to the contribution of the C.F.T.R.I. Dr. Kurien was made honorary member of the Association of food scientist and technologists (Journal of Food science and Technology,1965: 6, 49.) and in 1983 received the  Subrahmanyan Industrial Achievement Award (named after Dr.V.Subrahmanyan) by that Association.</div>
                <br></br>
                <div style={{ display: 'flex'}} >
                    <img src={amul1} height={280} width={280} />
                    <div style={{ marginLeft: '30px' }} ><img src={amul2} height={280} width={280} /></div>
                    <div style={{ marginLeft: '30px' }} ><img src={amul3} height={280} width={280} /></div>
                </div>

                <div className="earlylifepara" >In an advertisement in 1964 (Journal of Food Science and Technology, October 1964) "The certification of Amul Milk Food by the ISI necessarily involves high standards of production under strict quality control measures. These are in addition to regular quality testing by the Central Food Technological Research Institute. C.F.T.R.I. formulated Amul Milk Food after five years of research, to suit the special needs of babies in the tropics". The advertisement further catalogues the composition of the milk food and that the product was made from fresh milk" In another advertisement (Readers Digest October, volume 87 1965, page 26) is stated that "Amul Milk food has won the Kidwai  price and "Experts at the Central food Technological Research Institute formulated the Amul Milk food-to suit the food needs of babies in India and won the Kidwai Prize". Identical Advertisements to the one above is seen in the Indian Dairyman even up to 1967.The Kidwai price for formulating the baby food was given in 1960). Both advertisements discussed here and many others from that period show the blue tin and this as Kamath also accords, indicates the use of roller drying process to produce the food.  Material referring to the role of the C.F.T.R.I. in the development of the Baby food was also displayed on the tins. Amul spray was launched in 1968 (https://prsi.org.in/amul/) and the tins were painted in white.</div>
                <br></br>
                <div className="earlylifepara" >Dalaya and Patel (1974)(14) write "Research work carried out at the C.F.T.R.I., Mysore, conclusively established that buffalo milk can be processed into excellent baby food with lower curd tension, which is easily digestible and ideally suited for infant feeding.</div>
                <div className="earlylifepara" >They go on to state that initially in the roller drying process problems of solubility and reconstitution as well as problems of fat separation. These problems were solved and adopted during large scale preparation of roller dried infant food  (14). Dalaya (1921-2004) was very important in the development of the infant food at Anand and was Managing Director at Amul (http://bmvyas.blogspot.com/2017/04/hm-dalaya-silent-milk-man-of-india.html).</div>
                <br></br>
                <div className="earlylife" style={{ fontSize: 'larger' }} >Role of Larsen and Toubro</div>
                <br></br>
                <div>
                    <img style={{ float: 'left', margin: '15px' }} src={larsenandturbo} height={350} width={250} />
                    <div className="earlylifepara" >The Larsen and Toubro were agents for NIRO at that time and for a long time afterwards. The UNICEF also provided money for another spray dryer plant at Rajkot and according to the advertisement appended  ( Larsen and Toubro advertisement, Food Science 9 september, 1960) the Vijayawada dairy also obtained a NIRO spray dryer. The Larsen and Toubro and Niro joint venture continued in India till 2004 when  Niro A/S, Denmark, which is a part of GEA-the euro 3 billion major based in Germany, took over all assets in the country</div>
                    <div className="earlylifepara" >The milk committee reported that M/S. A.P.V. Engineering Company and M/S Larsen and Toubro had been license to manufacture "stainless steel hollow-ware, such as milk tanks, bath pasteurizers and other process vessels. Furthermore Larsen and Toubro were listed as agents for Silkeborg Maskin fabrik Denmark while TTK where agents for De Danske Mejeries Maskin fabrik, Koldin, Denmark</div>
                    <br></br>
                </div>
                <div className="earlylifepara" ><a href="/references" style={{ textDecoration: 'none' }} ><font color="#3819e9">References</font></a></div>
                <br></br><br></br>
                <Button size="small" style={{ color: 'white', fontWeight: 'bold', backgroundColor: 'darkblue', width: '155px', height: '35px' }} onClick={onClickHome} >Back to Home</Button>
            </div>
        </>
    )
}